spring:
  application:
    name: service-feign

server:
  port: 8040
  servlet:
      contextPath: /feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true

